name: Feature Request
description: Suggest an idea
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What do you want to see added or changed?
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why
      description: Why would this be useful?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Mockups, references, examples — anything helpful.
